include:
  - board: nice_nano_v2
    shield: hexen_dongle
  - board: nice_nano_v2
    shield: hexen_left
    extra-conf: |
      CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: hexen_right
    extra-conf: |
      CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: settings_reset