include:
  - board: nice_nano
    shield: hexen_dongle
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: hexen_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano
    shield: hexen_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano
    shield: settings_reset