include:
  # THE DONGLE (Central)
  - board: nice_nano_v2
    shield: hexen_dongle
  
  # LEFT HALF (Peripheral)
  - board: nice_nano_v2
    shield: hexen_left
    extra-conf: |
      CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  
  # RIGHT HALF (Peripheral)
  - board: nice_nano_v2
    shield: hexen_right
    extra-conf: |
      CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # SETTINGS RESET (Utility)
  - board: nice_nano_v2
    shield: settings_reset