# More power for the radio
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Delay boot for logs
#CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

# Fetch battery levels from the peripherals (the halves)
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n

# Enable deep sleep support
CONFIG_ZMK_SLEEP=y
# Idle timeout - 10 minutes
CONFIG_ZMK_IDLE_TIMEOUT=600000
# Deep sleep timeout - 45 minutes
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=2700000

# Enable battery monitoring hardware support
CONFIG_ZMK_BATTERY_REPORTING=y

# How often to update the battery level (in seconds)
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# Prospector display settings
# CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
# CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
# CONFIG_PROSPECTOR_LAYER_ROLLER_ALL_CAPS=y

# YADS Settings
CONFIG_DONGLE_SCREEN_SYSTEM_ICON=2
